# extract RGB frames
extract_rgb: true
# extract anonymization masks
extract_masks: true
# extract depth frames
extract_depth: true

extract_only_rgb_in_colmap: true
output_root: null

# folder where the data is downloaded
data_root: /network/scratch/a/adam.burhan/datasets/scannetpp/

splits: [nvs_sem_val]

# scene_ids: [09c1414f1b]
